name = "LaughPack"
author = "LaughingLeader"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "442e39e541773a4454cb81ab5d4da5e22213e5f1f0b2ee18f94ec56a8eb2d9f9"

[versions]
forge = "36.1.65"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16.5", "1.16.4"]
