name = "LaughPack"
author = "LaughingLeader"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c00df1ebcbfff9e0f1b2ace83fc7a91b8043543058f01cc34a384eb93494e8b0"

[versions]
forge = "36.1.65"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16.5", "1.16.4"]
