name = "LaughPack"
author = "LaughingLeader"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "80a8b11f79dd4c9168d52c51b251bd31d97732db9b1490784655ca5bb645d130"

[versions]
forge = "36.1.65"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16.5", "1.16.4"]
