name = "LaughPack"
author = "LaughingLeader"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d8495fb11d4e428cb7d9baba75c59708a044c22abce2cb4b9b479098dd828857"

[versions]
forge = "36.1.65"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16.5", "1.16.4"]
