name = "LaughPack"
author = "LaughingLeader"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c705ff26e2e2246e4091b06e47cdb59b96955e9c23829e597e3134d9b443138"

[versions]
forge = "36.1.65"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16.5", "1.16.4"]
