name = "Advancement Plaques"
filename = "AdvancementPlaques-1.16.5-1.3.1.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3429/631/AdvancementPlaques-1.16.5-1.3.1.jar"
hash-format = "murmur2"
hash = "180119487"

[update]
[update.curseforge]
file-id = 3429631
project-id = 499826
release-channel = "beta"
