name = "Advancement Plaques"
filename = "AdvancementPlaques-1.16.5-1.4.0.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3439/896/AdvancementPlaques-1.16.5-1.4.0.jar"
hash-format = "murmur2"
hash = "1843530684"

[update]
[update.curseforge]
file-id = 3439896
project-id = 499826
release-channel = "beta"
