name = "Advancement Plaques"
filename = "AdvancementPlaques-1.16.5-1.3.0.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3426/555/AdvancementPlaques-1.16.5-1.3.0.jar"
hash-format = "murmur2"
hash = "948702578"

[update]
[update.curseforge]
file-id = 3426555
project-id = 499826
release-channel = "beta"
