name = "Advanced Peripherals"
filename = "advancedperipherals-0.7a.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3402/710/advancedperipherals-0.7a.jar"
hash-format = "murmur2"
hash = "740193805"

[update]
[update.curseforge]
file-id = 3402710
project-id = 431725
release-channel = "beta"
