name = "Ars Nouveau"
filename = "ars_nouveau-1.16.5-1.22.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3439/724/ars_nouveau-1.16.5-1.22.1.jar"
hash-format = "murmur2"
hash = "4095175666"

[update]
[update.curseforge]
file-id = 3439724
project-id = 401955
release-channel = "beta"
