name = "Ars Nouveau"
filename = "ars_nouveau-1.16.5-1.21.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3430/906/ars_nouveau-1.16.5-1.21.3.jar"
hash-format = "murmur2"
hash = "1621711002"

[update]
[update.curseforge]
file-id = 3430906
project-id = 401955
release-channel = "beta"
