name = "Ars Nouveau"
filename = "ars_nouveau-1.16.5-1.21.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3420/925/ars_nouveau-1.16.5-1.21.1.jar"
hash-format = "murmur2"
hash = "1387536284"

[update]
[update.curseforge]
file-id = 3420925
project-id = 401955
release-channel = "beta"
