name = "Ars Nouveau"
filename = "ars_nouveau-1.16.5-1.22.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3440/396/ars_nouveau-1.16.5-1.22.2.jar"
hash-format = "murmur2"
hash = "2080569075"

[update]
[update.curseforge]
file-id = 3440396
project-id = 401955
release-channel = "beta"
