name = "Atum 2: Return to the Sands"
filename = "Atum-1.16.5-2.2.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3354/467/Atum-1.16.5-2.2.5.jar"
hash-format = "murmur2"
hash = "2586106011"

[update]
[update.curseforge]
file-id = 3354467
project-id = 59621
release-channel = "beta"
