name = "Atum 2: Return to the Sands"
filename = "Atum-1.16.5-2.2.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3406/907/Atum-1.16.5-2.2.6.jar"
hash-format = "murmur2"
hash = "3498609291"

[update]
[update.curseforge]
file-id = 3406907
project-id = 59621
release-channel = "beta"
