name = "Biomes O' Plenty"
filename = "BiomesOPlenty-1.16.5-13.1.0.481-universal.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3399/255/BiomesOPlenty-1.16.5-13.1.0.481-universal.jar"
hash-format = "murmur2"
hash = "612817815"

[update]
[update.curseforge]
file-id = 3399255
project-id = 220318
release-channel = "beta"
