name = "Blood Magic "
filename = "BloodMagic-1.16.4-3.1.2-17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3448/638/BloodMagic-1.16.4-3.1.2-17.jar"
hash-format = "murmur2"
hash = "1017084364"

[update]
[update.curseforge]
file-id = 3448638
project-id = 224791
release-channel = "beta"
