name = "CC: Tweaked"
filename = "cc-tweaked-1.16.5-1.98.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3408/528/cc-tweaked-1.16.5-1.98.0.jar"
hash-format = "murmur2"
hash = "160765736"

[update]
[update.curseforge]
file-id = 3408528
project-id = 282001
release-channel = "beta"
