name = "Chat Sound"
filename = "ChatSound-1.16.5-1.0.3.jar"
side = "client"

[option]
optional = true
description = "Adds sounds to Minecraft's chat. Plays sounds when you get a message. Plays a special sound when someone says your name."
default = true

[download]
url = "https://edge.forgecdn.net/files/3393/319/%5B1.16.5%5DChatSound-1.0.3.jar"
hash-format = "murmur2"
hash = "584050837"

[update]
[update.curseforge]
file-id = 3393319
project-id = 431628
release-channel = "beta"
