name = "Citadel"
filename = "citadel-1.8.0-1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3436/721/citadel-1.8.0-1.16.5.jar"
hash-format = "murmur2"
hash = "1032622022"

[update]
[update.curseforge]
file-id = 3436721
project-id = 331936
release-channel = "beta"
