name = "Claim Chunk"
filename = "ClaimChunk-1.16.2-1.0.0.9.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3396/619/ClaimChunk-1.16.2-1.0.0.9.jar"
hash-format = "murmur2"
hash = "1502526145"

[update]
[update.curseforge]
file-id = 3396619
project-id = 397443
release-channel = "beta"
