name = "CodeChicken Lib 1.8.+"
filename = "CodeChickenLib-1.16.5-4.0.2.427-universal.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3361/747/CodeChickenLib-1.16.5-4.0.2.427-universal.jar"
hash-format = "murmur2"
hash = "4227351526"

[update]
[update.curseforge]
file-id = 3361747
project-id = 242818
release-channel = "beta"
