name = "ColorUtility"
filename = "ColorUtility-1.16.5-forge-2.0.1serverfix.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3375/857/ColorUtility-%5B1.16.5%5D-forge-2.0.1serverfix.jar"
hash-format = "murmur2"
hash = "3519067798"

[update]
[update.curseforge]
file-id = 3375857
project-id = 259957
release-channel = "beta"
