name = "Compact Ores"
filename = "compactores-1.16.5-3.0.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3284/594/compactores-1.16.5-3.0.3.jar"
hash-format = "murmur2"
hash = "3947186883"

[update]
[update.curseforge]
file-id = 3284594
project-id = 354382
release-channel = "beta"
