name = "Corail Tombstone"
filename = "tombstone-1.16.5-6.5.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3452/229/tombstone-1.16.5-6.5.2.jar"
hash-format = "murmur2"
hash = "1159131114"

[update]
[update.curseforge]
file-id = 3452229
project-id = 243707
release-channel = "beta"
