name = "CraftTweaker"
filename = "CraftTweaker-1.16.5-7.1.0.384.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3423/629/CraftTweaker-1.16.5-7.1.0.384.jar"
hash-format = "murmur2"
hash = "1088468058"

[update]
[update.curseforge]
file-id = 3423629
project-id = 239197
release-channel = "beta"
