name = "CraftTweaker"
filename = "CraftTweaker-1.16.5-7.1.2.405.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3438/960/CraftTweaker-1.16.5-7.1.2.405.jar"
hash-format = "murmur2"
hash = "3811559706"

[update]
[update.curseforge]
file-id = 3438960
project-id = 239197
release-channel = "beta"
