name = "CraftTweaker"
filename = "CraftTweaker-1.16.5-7.1.0.371.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3415/429/CraftTweaker-1.16.5-7.1.0.371.jar"
hash-format = "murmur2"
hash = "935093834"

[update]
[update.curseforge]
file-id = 3415429
project-id = 239197
release-channel = "beta"
