name = "CraftTweaker"
filename = "CraftTweaker-1.16.5-7.1.0.366.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3409/220/CraftTweaker-1.16.5-7.1.0.366.jar"
hash-format = "murmur2"
hash = "1827374844"

[update]
[update.curseforge]
file-id = 3409220
project-id = 239197
release-channel = "beta"
