name = "CraftTweaker"
filename = "CraftTweaker-1.16.5-7.1.0.374.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3420/115/CraftTweaker-1.16.5-7.1.0.374.jar"
hash-format = "murmur2"
hash = "3559429368"

[update]
[update.curseforge]
file-id = 3420115
project-id = 239197
release-channel = "beta"
