name = "CraftTweaker"
filename = "CraftTweaker-1.16.5-7.1.1.402.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3437/151/CraftTweaker-1.16.5-7.1.1.402.jar"
hash-format = "murmur2"
hash = "659278573"

[update]
[update.curseforge]
file-id = 3437151
project-id = 239197
release-channel = "beta"
