name = "CraftTweaker"
filename = "CraftTweaker-1.16.5-7.1.1.399.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3432/52/CraftTweaker-1.16.5-7.1.1.399.jar"
hash-format = "murmur2"
hash = "3494370668"

[update]
[update.curseforge]
file-id = 3432052
project-id = 239197
release-channel = "beta"
