name = "CraftTweaker"
filename = "CraftTweaker-1.16.5-7.1.0.364.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3407/893/CraftTweaker-1.16.5-7.1.0.364.jar"
hash-format = "murmur2"
hash = "985062438"

[update]
[update.curseforge]
file-id = 3407893
project-id = 239197
release-channel = "beta"
