name = "CraftTweaker"
filename = "CraftTweaker-1.16.5-7.1.2.406.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3439/189/CraftTweaker-1.16.5-7.1.2.406.jar"
hash-format = "murmur2"
hash = "842543764"

[update]
[update.curseforge]
file-id = 3439189
project-id = 239197
release-channel = "beta"
