name = "CraftTweaker"
filename = "CraftTweaker-1.16.5-7.1.0.359.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3403/821/CraftTweaker-1.16.5-7.1.0.359.jar"
hash-format = "murmur2"
hash = "450755423"

[update]
[update.curseforge]
file-id = 3403821
project-id = 239197
release-channel = "beta"
