name = "Create"
filename = "create-mc1.16.5_v0.3.2c.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3406/857/create-mc1.16.5_v0.3.2c.jar"
hash-format = "murmur2"
hash = "1809305292"

[update]
[update.curseforge]
file-id = 3406857
project-id = 328085
release-channel = "beta"
