name = "Dark Caverns"
filename = "dark_caverns-1.16.5-1.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3430/422/dark_caverns-1.16.5-1.1.0.jar"
hash-format = "murmur2"
hash = "3096920242"

[update]
[update.curseforge]
file-id = 3430422
project-id = 508341
release-channel = "beta"
