name = "Dimensional Dungeons"
filename = "dimdungeons-1.13.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3407/168/dimdungeons-1.13.1.jar"
hash-format = "murmur2"
hash = "680680935"

[update]
[update.curseforge]
file-id = 3407168
project-id = 352222
release-channel = "beta"
