name = "Dynamic Trees"
filename = "DynamicTrees-1.16.5-0.10.0-Beta23.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3406/834/DynamicTrees-1.16.5-0.10.0-Beta23.jar"
hash-format = "murmur2"
hash = "1559527196"

[update]
[update.curseforge]
file-id = 3406834
project-id = 252818
release-channel = "beta"
