name = "Dynamic Music"
filename = "dynmus-1.3.1.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3392/990/dynmus-1.3.1.jar"
hash-format = "murmur2"
hash = "94172245"

[update]
[update.curseforge]
file-id = 3392990
project-id = 430824
release-channel = "beta"
