name = "Extreme Sound Muffler (Forge)"
filename = "extremeSoundMuffler-3.13-1.16.5.jar"
side = "client"

[option]
optional = true
description = "Extreme sound muffler is a mod that allows you to muffle sounds selectively, letting you to set the volume of individual sounds."
default = true

[download]
url = "https://edge.forgecdn.net/files/3345/51/extremeSoundMuffler-3.13-1.16.5.jar"
hash-format = "murmur2"
hash = "3352543717"

[update]
[update.curseforge]
file-id = 3345051
project-id = 363363
release-channel = "beta"
