name = "FerriteCore (Forge)"
filename = "ferritecore-2.0.6-forge.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3434/136/ferritecore-2.0.6-forge.jar"
hash-format = "murmur2"
hash = "2825173355"

[update]
[update.curseforge]
file-id = 3434136
project-id = 429235
release-channel = "beta"
