name = "Flywheel"
filename = "flywheel-1.16-0.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3406/855/flywheel-1.16-0.2.0.jar"
hash-format = "murmur2"
hash = "2623990562"

[update]
[update.curseforge]
file-id = 3406855
project-id = 486392
release-channel = "beta"
