name = "FTB Library (Forge)"
filename = "ftb-library-forge-1605.3.1-build.54.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3408/532/ftb-library-forge-1605.3.1-build.54.jar"
hash-format = "murmur2"
hash = "1562857978"

[update]
[update.curseforge]
file-id = 3408532
project-id = 404465
release-channel = "beta"
