name = "FTB Library (Forge)"
filename = "ftb-library-forge-1605.3.1-build.56.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3409/433/ftb-library-forge-1605.3.1-build.56.jar"
hash-format = "murmur2"
hash = "3506289796"

[update]
[update.curseforge]
file-id = 3409433
project-id = 404465
release-channel = "beta"
