name = "Fx Control!"
filename = "fxcontrol-1.16-2.0.12.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3422/27/fxcontrol-1.16-2.0.12.jar"
hash-format = "murmur2"
hash = "2324492577"

[update]
[update.curseforge]
file-id = 3422027
project-id = 313477
release-channel = "beta"
