name = "Game Stages"
filename = "GameStages-1.16.5-7.2.8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3348/627/GameStages-1.16.5-7.2.8.jar"
hash-format = "murmur2"
hash = "92174076"

[update]
[update.curseforge]
file-id = 3348627
project-id = 268655
release-channel = "beta"
