name = "GeckoLib"
filename = "geckolib-forge-1.16.5-3.0.43.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3403/668/geckolib-forge-1.16.5-3.0.43.jar"
hash-format = "murmur2"
hash = "3883408357"

[update]
[update.curseforge]
file-id = 3403668
project-id = 388172
release-channel = "beta"
