name = "Global Emeralds [Forge]"
filename = "Global_Emeralds1.16.54 .jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3414/947/Global_Emeralds1.16.54 .jar"
hash-format = "murmur2"
hash = "2710270123"

[update]
[update.curseforge]
file-id = 3414947
project-id = 504869
release-channel = "beta"
