name = "In Control!"
filename = "incontrol-1.16-5.2.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3447/816/incontrol-1.16-5.2.1.jar"
hash-format = "murmur2"
hash = "3972110840"

[update]
[update.curseforge]
file-id = 3447816
project-id = 257356
release-channel = "beta"
