name = "In Control!"
filename = "incontrol-1.16-5.1.9.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3360/637/incontrol-1.16-5.1.9.jar"
hash-format = "murmur2"
hash = "3421948715"

[update]
[update.curseforge]
file-id = 3360637
project-id = 257356
release-channel = "beta"
