name = "In Control!"
filename = "incontrol-1.16-5.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3422/26/incontrol-1.16-5.2.0.jar"
hash-format = "murmur2"
hash = "2979949957"

[update]
[update.curseforge]
file-id = 3422026
project-id = 257356
release-channel = "beta"
