name = "Iron Chests"
filename = "ironchest-1.16.5-11.2.12.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3405/339/ironchest-1.16.5-11.2.12.jar"
hash-format = "murmur2"
hash = "1933522008"

[update]
[update.curseforge]
file-id = 3405339
project-id = 228756
release-channel = "beta"
