name = "Item Stages"
filename = "ItemStages-Forge-1.16.5-3.0.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3433/122/ItemStages-Forge-1.16.5-3.0.3.jar"
hash-format = "murmur2"
hash = "3136625848"

[update]
[update.curseforge]
file-id = 3433122
project-id = 280316
release-channel = "beta"
