name = "Item Stages"
filename = "ItemStages-Forge-1.16.5-3.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3430/910/ItemStages-Forge-1.16.5-3.0.2.jar"
hash-format = "murmur2"
hash = "915883172"

[update]
[update.curseforge]
file-id = 3430910
project-id = 280316
release-channel = "beta"
