name = "Item Stages"
filename = "ItemStages-Forge-1.16.5-3.0.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3434/796/ItemStages-Forge-1.16.5-3.0.4.jar"
hash-format = "murmur2"
hash = "3543189097"

[update]
[update.curseforge]
file-id = 3434796
project-id = 280316
release-channel = "beta"
