name = "Item Stages"
filename = "ItemStages-Forge-1.16.5-3.0.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3439/46/ItemStages-Forge-1.16.5-3.0.6.jar"
hash-format = "murmur2"
hash = "1402348438"

[update]
[update.curseforge]
file-id = 3439046
project-id = 280316
release-channel = "beta"
