name = "It's the little things"
filename = "itlt-1.16.x-2.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3330/41/itlt-1.16.x-2.0.0.jar"
hash-format = "murmur2"
hash = "3019874326"

[update]
[update.curseforge]
file-id = 3330041
project-id = 232791
release-channel = "beta"
