name = "Just Enough Items (JEI)"
filename = "jei-1.16.5-7.7.1.117.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3411/420/jei-1.16.5-7.7.1.117.jar"
hash-format = "murmur2"
hash = "150777760"

[update]
[update.curseforge]
file-id = 3411420
project-id = 238222
release-channel = "beta"
