name = "Just Enough Items (JEI)"
filename = "jei-1.16.5-7.7.1.120.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3435/100/jei-1.16.5-7.7.1.120.jar"
hash-format = "murmur2"
hash = "2985537001"

[update]
[update.curseforge]
file-id = 3435100
project-id = 238222
release-channel = "beta"
