name = "JEITweaker"
filename = "JEITweaker-1.16.5-1.0.1.34.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3393/971/JEITweaker-1.16.5-1.0.1.34.jar"
hash-format = "murmur2"
hash = "716894697"

[update]
[update.curseforge]
file-id = 3393971
project-id = 368718
release-channel = "beta"
