name = "Just Enough Calculation"
filename = "JustEnoughCalculation-1.16.5-3.8.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3422/340/JustEnoughCalculation-1.16.5-3.8.4.jar"
hash-format = "murmur2"
hash = "1885099560"

[update]
[update.curseforge]
file-id = 3422340
project-id = 242223
release-channel = "beta"
