name = "KubeJS (Forge)"
filename = "kubejs-forge-1605.3.13-build.55.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3408/31/kubejs-forge-1605.3.13-build.55.jar"
hash-format = "murmur2"
hash = "204741490"

[update]
[update.curseforge]
file-id = 3408031
project-id = 238086
release-channel = "beta"
