name = "KubeJS (Forge)"
filename = "kubejs-forge-1605.3.15-build.73.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3423/702/kubejs-forge-1605.3.15-build.73.jar"
hash-format = "murmur2"
hash = "972802550"

[update]
[update.curseforge]
file-id = 3423702
project-id = 238086
release-channel = "beta"
