name = "KubeJS (Forge)"
filename = "kubejs-forge-1605.3.15-build.78.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3424/762/kubejs-forge-1605.3.15-build.78.jar"
hash-format = "murmur2"
hash = "893026543"

[update]
[update.curseforge]
file-id = 3424762
project-id = 238086
release-channel = "beta"
