name = "KubeJS (Forge)"
filename = "kubejs-forge-1605.3.13-build.50.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3407/442/kubejs-forge-1605.3.13-build.50.jar"
hash-format = "murmur2"
hash = "3572712288"

[update]
[update.curseforge]
file-id = 3407442
project-id = 238086
release-channel = "beta"
