name = "KubeJS (Forge)"
filename = "kubejs-forge-1605.3.14-build.67.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3419/118/kubejs-forge-1605.3.14-build.67.jar"
hash-format = "murmur2"
hash = "2152543902"

[update]
[update.curseforge]
file-id = 3419118
project-id = 238086
release-channel = "beta"
