name = "KubeJS (Forge)"
filename = "kubejs-forge-1605.3.15-build.104.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3443/663/kubejs-forge-1605.3.15-build.104.jar"
hash-format = "murmur2"
hash = "2171103761"

[update]
[update.curseforge]
file-id = 3443663
project-id = 238086
release-channel = "beta"
