name = "LibVulpes"
filename = "LibVulpes-1.16.5-1.0.2-26-universal.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3434/862/LibVulpes-1.16.5-1.0.2-26-universal.jar"
hash-format = "murmur2"
hash = "65950929"

[update]
[update.curseforge]
file-id = 3434862
project-id = 236541
release-channel = "beta"
