name = "ProgressivePeripherals"
filename = "progressiveperipherals-0.0.8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3424/996/progressiveperipherals-0.0.8.jar"
hash-format = "murmur2"
hash = "832366732"

[update]
[update.curseforge]
file-id = 3424996
project-id = 506252
release-channel = "beta"
