name = "ProgressivePeripherals"
filename = "progressiveperipherals-0.0.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3406/523/progressiveperipherals-0.0.4.jar"
hash-format = "murmur2"
hash = "2913207057"

[update]
[update.curseforge]
file-id = 3406523
project-id = 506252
release-channel = "beta"
