name = "ProgressivePeripherals"
filename = "progressiveperipherals-1.16.5-0.0.10.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3447/397/progressiveperipherals-1.16.5-0.0.10.jar"
hash-format = "murmur2"
hash = "1061469177"

[update]
[update.curseforge]
file-id = 3447397
project-id = 506252
release-channel = "beta"
