name = "ProgressivePeripherals"
filename = "progressiveperipherals-0.0.7.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3420/605/progressiveperipherals-0.0.7.jar"
hash-format = "murmur2"
hash = "2498483193"

[update]
[update.curseforge]
file-id = 3420605
project-id = 506252
release-channel = "beta"
