name = "ProgressivePeripherals"
filename = "progressiveperipherals-0.0.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3418/960/progressiveperipherals-0.0.6.jar"
hash-format = "murmur2"
hash = "3142247300"

[update]
[update.curseforge]
file-id = 3418960
project-id = 506252
release-channel = "beta"
