name = "Puzzles Lib"
filename = "PuzzlesLib-v1.0.11-1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3455/365/PuzzlesLib-v1.0.11-1.16.5.jar"
hash-format = "murmur2"
hash = "1616402311"

[update]
[update.curseforge]
file-id = 3455365
project-id = 495476
release-channel = "beta"
