name = "Puzzles Lib"
filename = "PuzzlesLib-v1.0.10-1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3396/597/PuzzlesLib-v1.0.10-1.16.5.jar"
hash-format = "murmur2"
hash = "2536041549"

[update]
[update.curseforge]
file-id = 3396597
project-id = 495476
release-channel = "beta"
