name = "Recipe Stages"
filename = "RecipeStages-2.0.0.20.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3442/297/RecipeStages-2.0.0.20.jar"
hash-format = "murmur2"
hash = "611420790"

[update]
[update.curseforge]
file-id = 3442297
project-id = 280554
release-channel = "beta"
