name = "Recipe Stages"
filename = "RecipeStages-2.0.0.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3395/210/RecipeStages-2.0.0.18.jar"
hash-format = "murmur2"
hash = "2909250167"

[update]
[update.curseforge]
file-id = 3395210
project-id = 280554
release-channel = "beta"
