name = "Refined Storage"
filename = "refinedstorage-1.9.14.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3400/209/refinedstorage-1.9.14.jar"
hash-format = "murmur2"
hash = "1536850551"

[update]
[update.curseforge]
file-id = 3400209
project-id = 243076
release-channel = "beta"
