name = "Relics"
filename = "relics-0.2.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3418/886/relics-0.2.5.jar"
hash-format = "murmur2"
hash = "2077567415"

[update]
[update.curseforge]
file-id = 3418886
project-id = 445274
release-channel = "beta"
