name = "Eric's Retail"
filename = "Retail-mc1.16-forge-0.3.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3403/723/Retail-mc1.16-forge-0.3.3.jar"
hash-format = "murmur2"
hash = "3583877876"

[update]
[update.curseforge]
file-id = 3403723
project-id = 431323
release-channel = "beta"
