name = "Rhino"
filename = "rhino-1605.1.2-build.46.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3426/334/rhino-1605.1.2-build.46.jar"
hash-format = "murmur2"
hash = "2300034072"

[update]
[update.curseforge]
file-id = 3426334
project-id = 416294
release-channel = "beta"
