name = "Refined Storage: Requestify"
filename = "rsrequestify-1.16.3-2.1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3408/394/rsrequestify-1.16.3-2.1.1.jar"
hash-format = "murmur2"
hash = "4138714175"

[update]
[update.curseforge]
file-id = 3408394
project-id = 307788
release-channel = "beta"
