name = "Simple Voice Chat"
filename = "voicechat-forge-1.16.5-1.7.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3396/958/voicechat-forge-1.16.5-1.7.2.jar"
hash-format = "murmur2"
hash = "1870327735"

[update]
[update.curseforge]
file-id = 3396958
project-id = 416089
release-channel = "beta"
