name = "Simple Voice Chat"
filename = "voicechat-forge-1.16.5-1.7.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3415/129/voicechat-forge-1.16.5-1.7.4.jar"
hash-format = "murmur2"
hash = "3739245440"

[update]
[update.curseforge]
file-id = 3415129
project-id = 416089
release-channel = "beta"
