name = "Simple Voice Chat"
filename = "voicechat-forge-1.16.5-1.7.8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3454/583/voicechat-forge-1.16.5-1.7.8.jar"
hash-format = "murmur2"
hash = "1196166745"

[update]
[update.curseforge]
file-id = 3454583
project-id = 416089
release-channel = "beta"
