name = "Simple Voice Chat"
filename = "voicechat-forge-1.16.5-1.7.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3395/838/voicechat-forge-1.16.5-1.7.0.jar"
hash-format = "murmur2"
hash = "2067845205"

[update]
[update.curseforge]
file-id = 3395838
project-id = 416089
release-channel = "beta"
