name = "Simple Voice Chat"
filename = "voicechat-forge-1.16.5-1.7.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3421/67/voicechat-forge-1.16.5-1.7.6.jar"
hash-format = "murmur2"
hash = "2352937938"

[update]
[update.curseforge]
file-id = 3421067
project-id = 416089
release-channel = "beta"
