name = "Simple Voice Chat"
filename = "voicechat-forge-1.16.5-1.7.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3418/893/voicechat-forge-1.16.5-1.7.5.jar"
hash-format = "murmur2"
hash = "51011774"

[update]
[update.curseforge]
file-id = 3418893
project-id = 416089
release-channel = "beta"
