name = "Small Ships"
filename = "smallships-1.16.5-1.9.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3407/325/smallships-1.16.5-1.9.2.jar"
hash-format = "murmur2"
hash = "3904050544"

[update]
[update.curseforge]
file-id = 3407325
project-id = 450659
release-channel = "beta"
