name = "Supplementaries"
filename = "supplementaries-1.16.5-0.15.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3420/570/supplementaries-1.16.5-0.15.1.jar"
hash-format = "murmur2"
hash = "2800175847"

[update]
[update.curseforge]
file-id = 3420570
project-id = 412082
release-channel = "beta"
