name = "Supplementaries"
filename = "supplementaries-1.16.5-0.15.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3415/392/supplementaries-1.16.5-0.15.0.jar"
hash-format = "murmur2"
hash = "2117907637"

[update]
[update.curseforge]
file-id = 3415392
project-id = 412082
release-channel = "beta"
