name = "Supplementaries"
filename = "supplementaries-1.16.5-0.15.1b.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3421/90/supplementaries-1.16.5-0.15.1b.jar"
hash-format = "murmur2"
hash = "2488778479"

[update]
[update.curseforge]
file-id = 3421090
project-id = 412082
release-channel = "beta"
