name = "Supplementaries"
filename = "supplementaries-1.16.5-0.15.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3422/581/supplementaries-1.16.5-0.15.2.jar"
hash-format = "murmur2"
hash = "1716584060"

[update]
[update.curseforge]
file-id = 3422581
project-id = 412082
release-channel = "beta"
