name = "TerraForged"
filename = "TerraForged-1.16.5-0.2.13.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3400/572/TerraForged-1.16.5-0.2.13.jar"
hash-format = "murmur2"
hash = "2558340777"

[update]
[update.curseforge]
file-id = 3400572
project-id = 363820
release-channel = "beta"
