name = "TerraForged"
filename = "TerraForged-1.16.5-0.2.14.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3414/123/TerraForged-1.16.5-0.2.14.jar"
hash-format = "murmur2"
hash = "2931295574"

[update]
[update.curseforge]
file-id = 3414123
project-id = 363820
release-channel = "beta"
