name = "TerraForged"
filename = "TerraForged-1.16.5-0.2.12.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3365/710/TerraForged-1.16.5-0.2.12.jar"
hash-format = "murmur2"
hash = "2494593053"

[update]
[update.curseforge]
file-id = 3365710
project-id = 363820
release-channel = "beta"
