name = "TerraForged"
filename = "TerraForged-1.16.5-0.2.15.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3451/426/TerraForged-1.16.5-0.2.15.jar"
hash-format = "murmur2"
hash = "1238608213"

[update]
[update.curseforge]
file-id = 3451426
project-id = 363820
release-channel = "beta"
