name = "Tetra Pak"
filename = "tetrapak-1.16.5-0.3.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3399/431/tetrapak-1.16.5-0.3.1.jar"
hash-format = "murmur2"
hash = "2870857370"

[update]
[update.curseforge]
file-id = 3399431
project-id = 463554
release-channel = "beta"
