name = "Tetra Pak"
filename = "tetrapak-0.3.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3401/450/tetrapak-0.3.2.jar"
hash-format = "murmur2"
hash = "1251288151"

[update]
[update.curseforge]
file-id = 3401450
project-id = 463554
release-channel = "beta"
