name = "Time Control"
filename = "timecontrol-1.16.5-1.1.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3429/434/timecontrol-1.16.5-1.1.2.0.jar"
hash-format = "murmur2"
hash = "1222505424"

[update]
[update.curseforge]
file-id = 3429434
project-id = 303570
release-channel = "beta"
