name = "Trample Stopper"
filename = "TrampleStopper-2.6.0-build.20+mc1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3431/952/TrampleStopper-2.6.0-build.20+mc1.16.5.jar"
hash-format = "murmur2"
hash = "53976052"

[update]
[update.curseforge]
file-id = 3431952
project-id = 297028
release-channel = "beta"
