name = "Traveler's Titles (Forge)"
filename = "TravelersTitles-1.16.4-1.5.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3398/20/TravelersTitles-1.16.4-1.5.jar"
hash-format = "murmur2"
hash = "2864210034"

[update]
[update.curseforge]
file-id = 3398020
project-id = 504908
release-channel = "beta"

[option]
optional = true
description = "Traveler's Titles is a simple client-side mod that adds RPG-like titles when entering biomes or dimensions. Completely customizable - change text size, color, location, duration, & more."
default = true
