name = "FTB Ranks (Forge)"
filename = "ftb-ranks-1605.1.4-build.9-forge.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3409/578/ftb-ranks-1605.1.4-build.9-forge.jar"
hash-format = "murmur2"
hash = "3937468688"

[update]
[update.curseforge]
file-id = 3409578
project-id = 314905
release-channel = "beta"
