name = "Slab Machines"
filename = "SlabMachines-1.16.5-1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3218/250/SlabMachines-1.16.5-1.1.jar"
hash-format = "murmur2"
hash = "450294238"

[update]
[update.curseforge]
file-id = 3218250
project-id = 301854
release-channel = "beta"
