name = "Transport"
filename = "Transport-1.16.5-3.7.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3386/772/Transport-1.16.5-3.7.0.jar"
hash-format = "murmur2"
hash = "893745118"

[update]
[update.curseforge]
file-id = 3386772
project-id = 292692
release-channel = "beta"
